//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryBook
    {
        public int BookId { get; set; }
        public string Title { get; set; }
        public string Serial_Number { get; set; }
        public string Author { get; set; }
        public string Publication { get; set; }
    }
}
