//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordsTable
    {
        public int customerId { get; set; }
        public int BookId { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int id { get; set; }
        public Nullable<bool> isApproved { get; set; }
    }
}
